version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
    groups:
      actions:
        patterns: ['*']
  - package-ecosystem: npm # reads pnpm-lock.yaml
    directory: '/'
    schedule:
      interval: daily
    ignore:
      - dependency-name: eslint
        versions: ['*']
      - dependency-name: typescript
        versions: ['*']
      - dependency-name: '@eslint/*'
        versions: ['*']
      - dependency-name: typescript-eslint
        versions: ['*']
      - dependency-name: gts
        versions: ['*']
