services:
  cli-psql-database:
    container_name: cli-psql-database
    platform: linux/amd64
    restart: unless-stopped
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - psql-data:/var/lib/postgresql/data
    ports:
      - '5434:5432'
    networks:
      - cli-db-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d mydb']
      interval: 5s
      timeout: 5s
      retries: 5

  cli-psql:
    container_name: cli-psql
    platform: linux/amd64
    restart: unless-stopped
    build:
      context: .
    depends_on:
      cli-psql-database:
        condition: service_healthy
    environment:
      DB_URL: postgres://postgres:postgres@cli-psql-database:5432/mydb
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
    command: ['sleep', 'infinity']
    networks:
      - cli-db-network

  cli-mysql-database:
    container_name: cli-mysql-database
    platform: linux/amd64
    restart: unless-stopped
    image: mysql:8.0
    environment:
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - '3307:3306'
    networks:
      - cli-db-network
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'mysqladmin ping -h localhost -u root -p$${MYSQL_ROOT_PASSWORD:-root} || exit 1',
        ]
      interval: 5s
      timeout: 5s
      retries: 5

  cli-mysql:
    container_name: cli-mysql
    platform: linux/amd64
    restart: unless-stopped
    build:
      context: .
    depends_on:
      cli-mysql-database:
        condition: service_healthy
    environment:
      DB_URL: mysql://mysql:mysql@cli-mysql-database:3306/mydb
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}
    command: ['sleep', 'infinity']
    networks:
      - cli-db-network

volumes:
  psql-data: {}
  mysql-data: {}

networks:
  cli-db-network:
    name: cli-db-network
    driver: bridge
