name: '[ CD ] | Tags'

on:
  workflow_dispatch:
    inputs:
      spec:
        description: The SEMVER specification.
        required: true
        type: choice
        default: patch
        options:
          - 'major'
          - 'minor'
          - 'patch'

permissions:
  id-token: write
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  setup-tags:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.version.outputs.tag }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - uses: heronlabs/build-tag-release-action@v2
        id: version
        with:
          github-token: ${{ secrets.PAT }}
          spec: ${{ inputs.spec }}
